### ISSUE TITLE
Season winners should be team based, not global

### ISSUE THREAD

**Issue by oyvinddd** [oyvinddd/officesports#61]
At the end of each month, we should loop through each team, saving the season winner for each team, instead of having one global winner.

I'll create a separate iOS/Android task for updating the 'season winners' UI in the app with a dropdown to show the season winner for each team.

**Comment by boyum** [comment]
In that case, we should probably store one season per team as well. Perhaps moving seasons into teams would make sense in the future, as they are strictly one-to-many.
