### ISSUE TITLE
Bugreport: iOS QR code

### ISSUE THREAD

**Issue by adneforslund** [oyvinddd/officesports#76]
Device: iPhone 12
OS: iOS 15.7

Problem: When clcking on profile image, no QR-code is generated, but shows instead a white square.

**Comment by oyvinddd** [comment]
Critical issue. Is this true for all three sports? What's your username (any special characters)? What happens if you log out/in again? @adneforslund

**Comment by adneforslund** [comment]
username: ådnis
it happens for all sports, bug also happens after logging in and out

**Comment by adneforslund** [comment]
Changed name from "ådnis" to "adnis", closed and opened app, and now it works

**Comment by oyvinddd** [comment]
I see.. seems like I need to add some logic for handling special characters ('å' etc.) when encoding data into the QR code. Thanks for your report.

**Comment by oyvinddd** [comment]
Fixed in latest version
