### ISSUE TITLE
Create possibility for registering duo matches

### ISSUE THREAD

**Issue by oyvinddd** [oyvinddd/officesports#82]

**Comment by boyum** [comment]
I've thought a bit about this before. I assume it's nVn matches. For scores, I've decided to do this:

```ts
const winnerAverageScore = winners.reduce((winner, sum) => sum += getScore(winner, sport), 0) / numberOfPlayersPerTeam;

const loserAverageScore = losers.reduce((loser, sum) => sum += getScore(loser, sport), 0) / numberOfPlayersPerTeam;

const eloDiff = elo(winnerAverageScore, loserAverageScore);

// This doesn't work, but you get the point
winners.forEach(winner => getScore(winner, sport) += eloDiff);
losers.forEach(loser => getScore(loser, sport) -= eloDiff);
```

The reason why I've decided to average the scores is to avoid huge point changes and I think it makes sense that each player on each team gets the same diff.

**Comment by oyvinddd** [comment]
Yes, my thought exactly :)! Needs to be averaged across players.

Request body can probably look something like this:

`
{
sport: 0,
winners: [uid1, uid2, ...],
losers: [uid3, uid4, ...]
}
`

**Comment by oyvinddd** [comment]
Need some brainstorming on how we best can create the UI in the app for this as well

**Comment by oyvinddd** [comment]
Flow:
1. One of the winners pulls up the camera
2. UI prompts winner to scan his/her partner
3. UI prompts the same person to scan the first loser
4. UI prompts the same person to scan the second loser
5. Match registration request is automatically sent
